### ISSUE TITLE
Add Main Function

### ISSUE THREAD

**Issue by NickKramer87** [rileeki-org/synthetic-database-project#69]
As a programmer, I want the driver code to be in a main() function to follow general best practices in python.

Acceptance Criteria:
1. Code that follows python best practices.

**Comment by TravisHaussler** [comment]
We reorganized the code into a arg parsing function followed by a main function within run_synthea.  

We also discussed structural changes to format.py so that pre-merge table generation and merge operations with the output_df could be unittested separately for each source file (procedures.csv, encounters, claims, etc), but opted not to do this at this time as it is not necessary for stage one production.
